version: '3.8'

services:
  reciveapi:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "8080:8080"

  backgroundworker:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
