version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  reciveapi:
    build:
      context: ../
      dockerfile: ReciveAPI/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672
      - ASPNETCORE_ENVIRONMENT=Development

  backgroundworker:
    build:
      context: ../
      dockerfile: BackgroundProcessWorker/Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672
      - ASPNETCORE_ENVIRONMENT=Development
